import type { Recipe, RecipeCategory } from "@/types";

export const CATEGORY_LABELS: Record<RecipeCategory, string> = {
  first: "Первые блюда",
  second: "Вторые блюда",
  side: "Гарниры",
  porridge: "Каши",
  salad: "Салаты",
  drink: "Напитки",
  bakery: "Выпечка",
  dessert: "Десерты",
  sauce: "Соусы",
};

// TODO: заменить на GET /api/recipes
export const RECIPES: Recipe[] = [
  {
    id: "r-borsch",
    name: "Борщ со сметаной",
    category: "first",
    image: "/images/dishes/borsch.jpg",
    cookTimeMin: 90,
    portionWeight: 250,
    nutrition: { calories: 220, protein: 6, fat: 7, carbs: 20 },
    ingredients: [
      { productId: "beet", amount: 60, unit: "г" },
      { productId: "cabbage", amount: 50, unit: "г" },
      { productId: "potato", amount: 50, unit: "г" },
      { productId: "carrot", amount: 20, unit: "г" },
      { productId: "onion", amount: 15, unit: "г" },
      { productId: "sourCream", amount: 15, unit: "г" },
    ],
    cooking: [
      "Сварить овощной бульон",
      "Добавить нашинкованную капусту, варить 10 минут",
      "Заложить пассерованную свёклу, морковь и лук",
      "Подавать со сметаной",
    ],
  },
  {
    id: "r-meatball-soup",
    name: "Суп с фрикадельками",
    category: "first",
    image: "/images/dishes/meatball-soup.jpg",
    cookTimeMin: 60,
    portionWeight: 250,
    nutrition: { calories: 240, protein: 9, fat: 8, carbs: 22 },
    ingredients: [
      { productId: "chicken", amount: 40, unit: "г" },
      { productId: "potato", amount: 40, unit: "г" },
      { productId: "carrot", amount: 15, unit: "г" },
      { productId: "onion", amount: 10, unit: "г" },
      { productId: "pasta", amount: 10, unit: "г" },
      { productId: "salt", amount: 1, unit: "г" },
    ],
    cooking: [
      "Приготовить фарш из филе и лука, скатать фрикадельки",
      "Довести воду до кипения, заложить картофель и морковь",
      "Опустить фрикадельки, варить 15 минут",
      "Добавить вермишель, посолить, варить ещё 5 минут",
    ],
  },
  {
    id: "r-oat",
    name: "Овсяная каша",
    category: "porridge",
    image: "/images/dishes/porridge.jpg",
    cookTimeMin: 30,
    portionWeight: 200,
    nutrition: { calories: 320, protein: 10, fat: 8, carbs: 45 },
    ingredients: [
      { productId: "oats", amount: 50, unit: "г" },
      { productId: "milk", amount: 150, unit: "мл" },
      { productId: "butter", amount: 5, unit: "г" },
      { productId: "sugar", amount: 8, unit: "г" },
      { productId: "salt", amount: 1, unit: "г" },
    ],
    cooking: [
      "Довести молоко до кипения",
      "Всыпать хлопья, варить 10 минут на слабом огне",
      "Добавить сахар, соль и масло, перемешать",
    ],
  },
  {
    id: "r-plov",
    name: "Плов из курицы",
    category: "second",
    image: "/images/dishes/plov.jpg",
    cookTimeMin: 80,
    portionWeight: 200,
    nutrition: { calories: 380, protein: 15, fat: 10, carbs: 48 },
    ingredients: [
      { productId: "rice", amount: 60, unit: "г" },
      { productId: "chicken", amount: 60, unit: "г" },
      { productId: "carrot", amount: 30, unit: "г" },
      { productId: "onion", amount: 15, unit: "г" },
      { productId: "oil", amount: 8, unit: "мл" },
      { productId: "garlic", amount: 2, unit: "г" },
      { productId: "salt", amount: 1, unit: "г" },
    ],
    cooking: [
      "Обжарить филе с луком и морковью",
      "Промыть рис, выложить ровным слоем",
      "Залить водой на два пальца выше риса",
      "Томить под крышкой 40 минут, дать настояться",
    ],
  },
  {
    id: "r-cutlet-puree",
    name: "Котлета куриная с пюре",
    category: "second",
    image: "/images/dishes/cutlet-puree.jpg",
    cookTimeMin: 60,
    portionWeight: 200,
    nutrition: { calories: 340, protein: 14, fat: 11, carbs: 32 },
    ingredients: [
      { productId: "chicken", amount: 70, unit: "г" },
      { productId: "potato", amount: 120, unit: "г" },
      { productId: "milk", amount: 30, unit: "мл" },
      { productId: "butter", amount: 5, unit: "г" },
      { productId: "egg", amount: 0.25, unit: "шт" },
      { productId: "salt", amount: 1, unit: "г" },
    ],
    cooking: [
      "Отварить картофель до мягкости",
      "Размять с горячим молоком и маслом",
      "Сформировать котлеты из фарша, запечь при 180°C 25 минут",
    ],
  },
  {
    id: "r-cutlet-rice",
    name: "Котлета куриная с рисом",
    category: "second",
    image: "/images/dishes/cutlet-rice.jpg",
    cookTimeMin: 60,
    portionWeight: 180,
    nutrition: { calories: 280, protein: 11, fat: 4, carbs: 30 },
    ingredients: [
      { productId: "chicken", amount: 70, unit: "г" },
      { productId: "rice", amount: 60, unit: "г" },
      { productId: "egg", amount: 0.25, unit: "шт" },
      { productId: "onion", amount: 10, unit: "г" },
      { productId: "oil", amount: 5, unit: "мл" },
      { productId: "salt", amount: 1, unit: "г" },
    ],
    cooking: [
      "Пропустить филе через мясорубку вместе с луком",
      "Добавить яйцо и соль, вымесить фарш",
      "Сформировать котлеты, запекать при 180°C 25 минут",
      "Отварить рис до готовности",
    ],
  },
  {
    id: "r-buckwheat-cutlet",
    name: "Гречка с котлетой",
    category: "second",
    image: "/images/dishes/buckwheat.jpg",
    cookTimeMin: 45,
    portionWeight: 200,
    nutrition: { calories: 360, protein: 16, fat: 10, carbs: 40 },
    ingredients: [
      { productId: "buckwheat", amount: 60, unit: "г" },
      { productId: "chicken", amount: 70, unit: "г" },
      { productId: "onion", amount: 10, unit: "г" },
      { productId: "oil", amount: 5, unit: "мл" },
      { productId: "butter", amount: 5, unit: "г" },
      { productId: "salt", amount: 1, unit: "г" },
    ],
    cooking: [
      "Перебрать и промыть гречку",
      "Залить водой 1:2, варить 20 минут под крышкой",
      "Заправить сливочным маслом",
      "Запечь котлеты при 180°C 25 минут",
    ],
  },
  {
    id: "r-pasta-cheese",
    name: "Макароны с сыром",
    category: "side",
    image: "/images/dishes/pasta-cheese.jpg",
    cookTimeMin: 25,
    portionWeight: 180,
    nutrition: { calories: 300, protein: 11, fat: 9, carbs: 42 },
    ingredients: [
      { productId: "pasta", amount: 70, unit: "г" },
      { productId: "cheese", amount: 20, unit: "г" },
      { productId: "butter", amount: 5, unit: "г" },
      { productId: "salt", amount: 1, unit: "г" },
    ],
    cooking: [
      "Отварить макароны в подсоленной воде до аль денте",
      "Откинуть на дуршлаг, заправить маслом",
      "Посыпать тёртым сыром и перемешать",
    ],
  },
  {
    id: "r-yogurt",
    name: "Йогурт с фруктами",
    category: "dessert",
    image: "/images/dishes/yogurt.jpg",
    cookTimeMin: 15,
    portionWeight: 150,
    nutrition: { calories: 150, protein: 6, fat: 4, carbs: 20 },
    ingredients: [
      { productId: "yogurt", amount: 120, unit: "г" },
      { productId: "berries", amount: 40, unit: "г" },
    ],
    cooking: ["Промыть и нарезать фрукты", "Выложить в креманку, залить йогуртом"],
  },
  {
    id: "r-casserole",
    name: "Запеканка творожная с изюмом",
    category: "bakery",
    image: "/images/dishes/casserole.jpg",
    cookTimeMin: 60,
    portionWeight: 180,
    nutrition: { calories: 380, protein: 13, fat: 6, carbs: 18 },
    ingredients: [
      { productId: "curd", amount: 120, unit: "г" },
      { productId: "raisins", amount: 15, unit: "г" },
      { productId: "egg", amount: 0.5, unit: "шт" },
      { productId: "sugar", amount: 10, unit: "г" },
      { productId: "butter", amount: 5, unit: "г" },
    ],
    cooking: [
      "Замочить изюм в тёплой воде на 10 минут",
      "Растереть творог с яйцом и сахаром",
      "Добавить изюм, выложить в смазанную форму",
      "Запекать при 180°C 30 минут",
    ],
  },
  {
    id: "r-compote",
    name: "Компот из сухофруктов",
    category: "drink",
    image: "/images/dishes/compote.jpg",
    cookTimeMin: 25,
    portionWeight: 200,
    nutrition: { calories: 50, protein: 1, fat: 1, carbs: 5 },
    ingredients: [
      { productId: "driedFruit", amount: 30, unit: "г" },
      { productId: "sugar", amount: 10, unit: "г" },
    ],
    cooking: [
      "Промыть сухофрукты тёплой водой",
      "Залить водой, довести до кипения",
      "Добавить сахар, варить 20 минут",
      "Дать настояться и остыть",
    ],
  },
  {
    id: "r-tea",
    name: "Чай с молоком",
    category: "drink",
    image: "/images/dishes/tea.jpg",
    cookTimeMin: 10,
    portionWeight: 200,
    nutrition: { calories: 60, protein: 1, fat: 1, carbs: 5 },
    ingredients: [
      { productId: "tea", amount: 1, unit: "г" },
      { productId: "milk", amount: 30, unit: "мл" },
      { productId: "sugar", amount: 5, unit: "г" },
    ],
    cooking: ["Заварить чай, дать настояться 5 минут", "Добавить тёплое молоко и сахар"],
  },
];

export const RECIPES_BY_ID = new Map(RECIPES.map((r) => [r.id, r]));

export function getRecipe(id: string): Recipe | undefined {
  return RECIPES_BY_ID.get(id);
}